# Generated by Django 3.2.7 on 2021-12-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
    ]
